#!/bin/sh
# Script to configure X, start common apps, and start xmonad.
# Author: Vic Fryzel
# https://github.com/vicfryzel/xmonad-config


# Configure PATH so that we can access our scripts below
PATH=$PATH:~/.cabal/bin:~/.xmonad/bin

# Configure X
xsetroot -cursor_name left_ptr &
xrdb ~/.Xresources &
xset r rate 190 35 &
xinput set-prop "Razer Razer Abyssus" 314 -1 &
setxkbmap "lv,ru" option grp:caps_toggle &
unclutter &

# Start a window compositor. This ensures Google Chrome paints correctly.
xcompmgr -n &

# Set a wallpaper
feh --bg-fill ~/.wallpaper.jpg &

# Start the system tray
#stalonetray -c ~/.xmonad/stalonetrayrc-single &

# Start screensaver
killall gnome-screensaver &
xscreensaver -no-splash &

# Start sound server
# pulseaudio --start --log-target=syslog &

# Important stuff
autocutsel &
autocutsel -s PRIMARY &

exec dbus-launch --sh-syntax --exit-with-session xmonad
